
//{{AFX_CODEJOCK_PRIVATE

#ifndef _XTP_SCHEMA_CURRENT

#define _XTP_SCHEMA_71  (0x1)
#define _XTP_SCHEMA_80  (0x2)
#define _XTP_SCHEMA_85  (0x3)
#define _XTP_SCHEMA_86  (0x4)
#define _XTP_SCHEMA_861 (0x5)
#define _XTP_SCHEMA_87  (0x6)
#define _XTP_SCHEMA_875 (0x7)
#define _XTP_SCHEMA_95  (0x8)
#define _XTP_SCHEMA_97  (0x9)
#define _XTP_SCHEMA_98  (0x10)
#define _XTP_SCHEMA_100 (0x11)
#define _XTP_SCHEMA_103 (0x12)
#define _XTP_SCHEMA_104 (0x14)
#define _XTP_SCHEMA_1041 (0x15)
#define _XTP_SCHEMA_1042 (0x16)
#define _XTP_SCHEMA_110 (0x17)
#define _XTP_SCHEMA_112 (0x18)
#define _XTP_SCHEMA_1121 (0x19)
#define _XTP_SCHEMA_1122 (0x20)
#define _XTP_SCHEMA_1200 (0x21)
#define _XTP_SCHEMA_1210 (0x22)
#define _XTP_SCHEMA_1300 (0x23)
#define _XTP_SCHEMA_1310 (0x24)
#define _XTP_SCHEMA_1340 (0x25)
#define _XTP_SCHEMA_1500 (0x26)


#define _XTP_SCHEMA_CURRENT _XTP_SCHEMA_1500

#endif

//}}AFX_CODEJOCK_PRIVATE
